image: docker:latest

variables:

services:
  - docker:dind

before_script:

stages:
  - test
  - publish

test_nmp_package:
  stage: test
  before_script:
    - apk add --no-cache npm
  script:
    - npm install
    - npm run build
    - npm test

publish_npm_package:
  stage: publish
  before_script:
    - apk add --no-cache npm
  script:
    - npm install
    - npm run build
    - npm config set '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'
    - npm publish --access public
  only:
    refs:
    - master
