export const LAYERMANAGER_TOGGLE_LAYERSELECTOR = 'LAYERMANAGER_TOGGLE_LAYERSELECTOR';
export const LAYERMANAGER_TOGGLE_STYLESSELECTOR = 'LAYERMANAGER_TOGGLE_STYLESSELECTOR';
export const LAYERMANAGER_SET_NUMBER_OF_LAYERS = 'LAYERMANAGER_SET_NUMBER_OF_LAYERS';
export const LAYERMANAGER_SET_TIMERESOLUTION = 'LAYERMANAGER_SET_TIMERESOLUTION';
export const LAYERMANAGER_SET_TIMEVALUE = 'LAYERMANAGER_SET_TIMEVALUE';
export const LAYER_MANAGER_EMPTY_LAYER = {
  layerSelectorOpen: false
};
